##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

##############################################################################################
# Playbook to create deployment files for namespaces, service account and clusterrolebinding
# Playbook arguments: complete network.yaml
##############################################################################################

- hosts: ansible_provisioners
  gather_facts: no
  no_log: "{{ no_ansible_log | default(false) }}"
  tasks:    
  # Delete build directory
  - name: Remove build directory
    file:
      path: "./build"
      state: absent

  # create namespace
  - name: "Create namespace"
    include_role: 
      name: create/namespace 
    loop: "{{ network['organizations'] }}"
    loop_control:
      loop_var: org

  # Create Storageclass
  - name: Create StorageClass
    include_role:
      name: "{{ playbook_dir }}/../../../platforms/shared/configuration/roles/setup/storageclass"
    vars:
      org_name: "{{ org.name | lower }}"
      sc_name: "{{ org_name }}-bevel-storageclass" 
      region: "{{ org.k8s.region | default('eu-west-1') }}"
    loop: "{{ network['organizations'] }}"
    loop_control:
      loop_var: org

  # Setup Vault-Kubernetes accesses
  - name: "Setup vault Kubernetes accesses"
    include_role:
      name: "{{ playbook_dir }}/../../shared/configuration/roles/setup/vault_kubernetes"
    vars:
      name: "{{ item.name | lower }}"
      org_name: "{{ item.name | lower }}"
      component_ns: "{{ item.name | lower }}-ns"
      component_name: "{{ item.name | lower }}-vaultk8s-job"
      component_auth: "{{ network.env.type }}{{ name }}"
      component_type: "organization"
      kubernetes: "{{ item.k8s }}"
      vault: "{{ item.vault }}"
      gitops: "{{ item.gitops }}"
    loop: "{{ network['organizations'] }}"

  # Deploy Doorman node
  - name: Deploy Doorman service node
    include_role:
      name: setup/doorman
    vars:
      services: "{{ item.services }}"
      name: "{{ item.name | lower }}"
      sc_name: "{{ name }}-bevel-storageclass"
      component_ns: "{{ item.name | lower }}-ns"
      kubernetes: "{{ item.k8s }}"
      vault: "{{ item.vault }}"
      gitops: "{{ item.gitops }}"     
    loop: "{{ network['organizations'] }}"
    when: item.type.find('doorman') != -1

  # Deploy NMS node
  - name: Deploy Networkmap service node
    include_role:
      name: setup/nms      
    vars:
      services: "{{ item.services }}"
      name: "{{ item.name | lower }}"
      sc_name: "{{ name }}-bevel-storageclass"
      component_ns: "{{ item.name | lower }}-ns"
      kubernetes: "{{ item.k8s }}"
      vault: "{{ item.vault }}"
      gitops: "{{ item.gitops }}"
    loop: "{{ network['organizations'] }}"
    when: item.type.find('nms') != -1
  
  # Wait for network services to respond  
  - name: Check that network services uri are reachable
    uri:
      url: "{{ item.uri }}"
      validate_certs: no
    register: this
    until: this.status == 200 or this.status == 401
    loop: "{{ network['network_services'] }}"
    retries: "{{ network.env.retry_count}}"
    delay: 50
    ignore_errors: yes
    when: network.env.proxy != 'none'

  # Deploy notaries
  - name: 'Deploy notary'
    include_role:
      name: setup/notary
    vars:
      services: "{{ item.services }}"
      node: "{{ item.services.notary }}"
      name: "{{ item.name | lower }}"
      sc_name: "{{ name }}-bevel-storageclass"
      component_ns: "{{ item.name | lower }}-ns"
      kubernetes: "{{ item.k8s }}"
      vault: "{{ item.vault }}"
      gitops: "{{ item.gitops }}" 
      cordapps: "{{ item.cordapps | default() }}"
    loop: "{{ network['organizations'] }}"
    when: item.type.find('notary') != -1

  # Deploy all other nodes
  - name: 'Deploy nodes'
    include_role:
      name: setup/node
    vars:
      name: "{{ item.name | lower }}"
      sc_name: "{{ name }}-bevel-storageclass"
      component_ns: "{{ item.name | lower }}-ns"
      services: "{{ item.services }}"
      kubernetes: "{{ item.k8s }}"
      vault: "{{ item.vault }}"
      cordapps: "{{ item.cordapps | default() }}"
      gitops: "{{ item.gitops }}" 
    loop: "{{ network['organizations'] }}"  
    when: item.type == 'node'
