##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

#############################################################################################
# This role deletes the Vault configurations
#############################################################################################

# Delete the Docker credentials
- name: Delete docker creds
  k8s:
    kind: Secret
    namespace: "{{ component_name }}"
    name: "regcred"
    state: absent
    kubeconfig: "{{ kubernetes.config_file }}"
    context: "{{ kubernetes.context }}"
  ignore_errors: yes
  changed_when: false

# Delete service creds
- name: "Delete service creds"
  include_tasks: nested_main.yaml
  loop: "{{ services | dict2items }}"
  loop_control:
    loop_var: service
  when: component_type != 'node'

# Delete the Ambassador Creds
- name: Delete Ambassador creds
  k8s:
    kind: Secret
    namespace: "{{ component_name }}"
    name: "{{ node.name }}-ambassador-certs"
    kubeconfig: "{{ kubernetes.config_file }}"
    context: "{{ kubernetes.context }}"
    state: absent
  loop: "{{ services.peers }}"
  loop_control:
    loop_var: node
  when: component_type == 'node'
  ignore_errors: yes
  changed_when: false

# Delete crypto materials from vault
- name: Delete Crypto for nodes
  shell: |
    vault secrets disable {{ item.vault.secret_path | default(item.name) }}
  environment:
    VAULT_ADDR: "{{ item.vault.url }}"
    VAULT_TOKEN: "{{ item.vault.root_token }}"
