##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: {{ .Values.nodeName }}db
    {{- if .Values.deployment.annotations }}
    annotations:
{{ toYaml .Values.deployment.annotations | indent 8 }}
    {{- end }}
    namespace: {{ .Values.metadata.namespace }}
    labels:
      app.kubernetes.io/name: {{ .Values.nodeName }}db
      helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app.kubernetes.io/instance: {{ .Release.Name }} 
spec:
    serviceName: {{ .Values.nodeName }}db
    replicas: 1
    selector:
      matchLabels:
        app: {{ .Values.nodeName }}db
        app.kubernetes.io/name: {{ .Values.nodeName }}db
        app.kubernetes.io/instance: {{ .Release.Name }}
    updateStrategy:
      type: OnDelete
    template:
      metadata:
        labels:
          app: {{ .Values.nodeName }}db
          app.kubernetes.io/name: {{ .Values.nodeName }}db
          app.kubernetes.io/instance: {{ .Release.Name }}
      spec:
        hostname: {{ .Values.nodeName }}db
        securityContext:
          fsGroup: 1000
        containers:
        - name: {{ .Values.nodeName }}db
          image: {{ .Values.image.containerName }}
          resources:
            limits:
              memory: {{ .Values.resources.limits }}
            requests:
              memory: {{ .Values.resources.requests }}
          ports:
            - containerPort: 1521
              name: p2p
            - containerPort: 81
              name: web
          env:
            - name: JAVA_OPTIONS
              value: -Xmx512m
          volumeMounts:
          - name: {{ .Values.nodeName }}db-pvc
            mountPath: "/opt/h2-data"
            readOnly: false
          livenessProbe:
            tcpSocket:
              port: 1521
            initialDelaySeconds: 15
            periodSeconds: 20
        imagePullSecrets:
          - name: {{ .Values.image.imagePullSecret }}
    volumeClaimTemplates: 
      - metadata:
          name: {{ .Values.nodeName }}db-pvc
  {{- if .Values.pvc.annotations }}
          annotations:
  {{ toYaml .Values.pvc.annotations | indent 8 }}
  {{- end }}
          labels:
            app.kubernetes.io/name: {{ .Values.nodeName }}db-pvc
            helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
            app.kubernetes.io/managed-by: {{ .Release.Service }}
            app.kubernetes.io/instance: {{ .Release.Name }}
        spec:
          storageClassName: {{ .Values.storage.name }}
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: {{ .Values.storage.memory }}
