apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oem-ipfs-bn-ipfs-node
  namespace: oem-subs
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: oem-ipfs-bn-ipfs-node
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dscp
        namespace: flux-dscp
      chart: platforms/substrate/charts/dscp-ipfs-node
  values:
    fullnameOverride: oem-ipfs-bn-ipfs
    namespace: oem-subs
    config:
      healthCheckPort: 80
      healthCheckPollPeriod: 30000
      healthCheckTimeout: 2000
      nodeHost: "oem-bn"
      nodePort: "9944"
      logLevel: info
      ipfsApiPort: 5001
      ipfsSwarmPort: 4001
      ipfsDataPath: "/ipfs"
      ipfsCommand: "/usr/local/bin/ipfs"
      ipfsArgs:
        - daemon
        - "--migrate"
      ipfsSwarmAddrFilters: null
      ipfsLogLevel: info
      
    service:
      swarm:
        annotations: {}
        enabled: true
        port: 4001
      api:
        annotations: {}
        enabled: true
        port: 5001

    statefulSet:
      annotations: {}
      livenessProbe:
        enabled: true
    image:
      repository: ghcr.io/inteli-poc/dscp-ipfs
      pullPolicy: IfNotPresent
      tag: 'v2.6.2'
    storage:
      storageClass: "oem-bevel-storageclass"
      dataVolumeSize: 20  # in Gigabytes
    dscpNode:
      enabled: false
    proxy:
      provider: ambassador
      external_url: oem-ipfs-bn-ipfs-swarm.dev.intelipoc.com
      port: 15014
      certSecret: oem-ambassador-certs
    vault:
      address: http://inteli-vault.dev.intelipoc.com
      role: vault-role
      authpath: dscpoem
      serviceaccountname: vault-auth
      certsecretprefix: secretsv2/data/oem/oem-ipfs-bn
