fullNameOverride:
config:
  externalNodeHost:
  externalPostgresql:
  port: 
  logLevel: 
  dbName: 
  dbPort: 
  enableLivenessProbe: true
  selfAddress: 
  auth:
    type: 
    jwksUri: 
    audience: 
    issuer:

ingress:
  enabled: false
  # annotations: {}
  # className
  paths:
    - /v1/members

replicaCount: 1

image:
  repository: 
  pullPolicy: 
  tag: 
  pullSecrets: 

postgresql:
  enabled: false
  postgresqlDatabase: 
  postgresqlUsername: 
  postgresqlPassword: 
dscpNode:
  enabled: false
vault:
  alpineutils: ghcr.io/hyperledger/alpine-utils:1.0
  address:
  secretprefix:
  serviceaccountname:
  role:
  authpath:
