##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

certificate:
  email: someone@example.com
  issuedFor:
