##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

---
# Check if istio is already installed
- name: "Check if istio is already installed"
  k8s_info:
    kind: Pod
    namespace: "istio-system"
    kubeconfig: "{{ kubeconfig_path }}"
    context: "{{ kubecontext }}"
    label_selectors:
      - app=istio-ingressgateway
    field_selectors:
      - status.phase=Running
  register: istio_status

# Set istio installed fact
- name: Set istio installed fact
  set_fact:
    istio_installed: "{{ istio_status.resources | length > 0 }}"

# Install istio ingress via helmchart
- name: Install istio Ingress controller
  shell: |
    KUBECONFIG={{ kubeconfig_path }} helm repo add istio https://istio-release.storage.googleapis.com/charts --force-update
    KUBECONFIG={{ kubeconfig_path }} helm repo update
    KUBECONFIG={{ kubeconfig_path }} helm install istio-base istio/base -n istio-system --create-namespace
    KUBECONFIG={{ kubeconfig_path }} helm install istiod istio/istiod -n istio-system --wait
    KUBECONFIG={{ kubeconfig_path }} helm install istio-ingressgateway istio/gateway -n istio-system
  when: (not istio_installed)
  tags:
    - istio

# Update external_dns with correct annotations
- name: Enable external DNS
  shell: |
    KUBECONFIG={{ kubeconfig_path }} kubectl annotate service istio-ingressgateway -n istio-system --overwrite "external-dns.alpha.kubernetes.io/hostname=*.{{ item.external_url_suffix }}."
  tags:
    - istio
  when: network.env.external_dns is defined and network.env.external_dns == 'enabled'

# Wait for istio pods to start running
- name: Wait for pods to come up
  include_role:
    name: "check/helm_component"
  vars:
    namespace: istio-system
    kubeconfig: "{{ kubeconfig_path }}"
    context: "{{ kubecontext }}"
    component_name: istio
    component_type: "Pod"
    label_selectors:
      - app=istio-ingressgateway
