##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

job_templates:
  primary_genesis: primary_genesis.tpl
  secondary_genesis: secondary_genesis.tpl
charts:
  primary_genesis: besu-genesis
  secondary_genesis: besu-genesis
