fullnameOverride:
config:
  port: 
  externalPostgresql: 
  dscpApiHost: 
  dscpApiPort: 
  logLevel: 
  dbName: 
  dbPort: 
  identityServiceHost: 
  identityServicePort: 
  externalAddress: 
  auth:
    type: 
    jwksUri: 
    audience: 
    issuer:
    tokenUrl: 

deployment:
  annotations: {}
  livenessProbe:
    enabled: true
  replicaCount: 1

ingress:
  enabled: false
  annotations: {}
  # className: ""
  paths:
    - /v1/attachment
    - /v1/build
    - /v1/order
    - /v1/part
    - /v1/recipe

service:
  annotations: {}
  enabled: false
  port: 

image:
  repository: ghcr.io/digicatapult/inteli-api
  pullPolicy: IfNotPresent
  tag: 'v1.28.0'
  pullSecrets: 

postgresql:
  enabled: false
  postgresqlDatabase: 
  postgresqlUsername: 
  postgresqlPassword: 
