##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

---
# Task to check if Namespace, Clusterrolebinding or StorageClass is created
# This task will try for a maximum number of iterations defined in env.retry_count of network.yaml with an interval of
# 35 seconds between each try

# Check if component created without retry
- name: Check {{ component_type }} {{ component_name }} is created
  k8s_info:
    kind: "{{ component_type }}"
    name: "{{ component_name }}"
    kubeconfig: "{{ kubernetes.config_file }}"
    context: "{{ kubernetes.context }}"
  register: result
  when: 
    - component_type == "Namespace" or component_type == "StorageClass" or component_type == "ClusterRoleBinding"
    - type == "no_retry"

# Check if a component is created with retry
- name: Wait for {{ component_type }} {{ component_name }}
  k8s_info:
    kind: "{{ component_type }}"
    name: "{{ component_name }}"
    kubeconfig: "{{ kubernetes.config_file }}"
    context: "{{ kubernetes.context }}"
  register: component_data
  retries: "{{ network.env.retry_count }}"
  delay: 35
  until: component_data.resources|length > 0
  when: 
    - component_type == "Namespace" or component_type == "ClusterRoleBinding" or component_type == "StorageClass"
    - type is undefined or type == "retry"

# Task to check if ServiceAccount is created
# This task will try for a maximum number of iterations defined in env.retry_count of network.yaml with an interval of
# 35 seconds between each try
- name: Check {{ component_type }} {{ component_name }} is created
  k8s_info:
    kind: "{{ component_type }}"
    name: "{{ component_name }}"
    namespace: "{{ component_ns }}"
    kubeconfig: "{{ kubernetes.config_file }}"
    context: "{{ kubernetes.context }}"
  register: serviceAccount_data
  when: (component_type == "ServiceAccount" and type == "no_retry")

# Task to check if ServiceAccount is created
# This task will try for a maximum number of iterations defined in env.retry_count of network.yaml with an interval of
# 35 seconds between each try
- name: Wait for {{ component_type }} {{ component_name }}
  k8s_info:
    kind: "{{ component_type }}"
    name: "{{ component_name }}"
    namespace: "{{ component_ns }}"
    kubeconfig: "{{ kubernetes.config_file }}"
    context: "{{ kubernetes.context }}"
  register: component_data
  retries: "{{ network.env.retry_count }}"
  delay: 35
  until: component_data.resources|length > 0
  when: (component_type == "ServiceAccount" and (type is undefined or type == 'retry'))
