##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

helm_templates:
  dscp-api: dscp-api.tpl
  dscp-frontend: dscp-frontend.tpl
  certissuer: certissuer.tpl
  postgresql: postgresql.tpl
  dscp-id-service: dscp-id-service.tpl
  inteli-api: inteli-api.tpl
  dscp-chain-watcher: dscp-chain-watcher.tpl
  fluxautomation: flux_automation.tpl
