##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chain-watcher.fullname" . }}-config
data:
  dscpApiHost: {{ .Values.config.dscpApiHost }}
  dscpApiPort: {{ .Values.config.dscpApiPort | quote }}
  dbHost: {{ .Values.config.dbHost }}
  dbPort: {{ .Values.config.dbPort | quote }}
  dbName: {{ .Values.config.dbName }}
  idServiceHost: {{ .Values.config.idServiceHost }}
  idServicePort: {{ .Values.config.idServicePort | quote }}
  inteliApiHost: {{ .Values.config.inteliApiHost }}
  inteliApiPort: {{ .Values.config.inteliApiPort | quote }}
  fetchGcpKey: {{ .Values.config.fetchGcpKey | quote }}
