##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "chain-watcher.fullname" . }}-db-migration
  labels:
    app.kubernetes.io/name: {{ include "chain-watcher.fullname" . }}-db-migration
spec:
  backoffLimit: 6
  template:
    metadata:
      labels:
        app: {{ include "chain-watcher.fullname" . }}
        app.kubernetes.io/name: {{ include "chain-watcher.fullname" . }}-db-migration
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      restartPolicy: OnFailure
      securityContext:
        fsGroup: 1000
      containers:
        - name: {{ include "chain-watcher.fullname" . }}-db-migration
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command: [ 'npx', 'knex', "migrate:latest"]
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "chain-watcher.fullname" . }}-config
                  key: dbHost
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "chain-watcher.fullname" . }}-config
                  key: dbPort
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "chain-watcher.fullname" . }}-config
                  key: dbName
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "chain-watcher.fullname" . }}-secret
                  key: dbUsername
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "chain-watcher.fullname" . }}-secret
                  key: dbPassword
