##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chain-watcher.fullname" . }}-secret
data:
  dbUsername: {{ .Values.config.dbUsername | b64enc | quote }}
  dbPassword: {{ .Values.config.dbPassword | b64enc | quote }}
