##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
appVersion: "2.0"
description: "Hyperledger Fabric: Updates the anchorpeer details."
name: fabric-anchorpeer
version: 1.0.0
