##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# Wait for namespace to be created by flux
- name: "Wait for the namespace {{ component_ns }} to be created"
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/check/k8_component"
  vars:
    component_type: "Namespace"
    component_name: "{{ component_ns }}"
    type: "retry"

# Create the vault roottoken secret
- name: "Create vault token secret"
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/create/shared_k8s_secrets"
  vars: 
    namespace: "{{ component_ns }}"    
    check: "token_secret"

# Create the docker pull credentials for image registry
- name: "Create docker credentials secret"
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/create/shared_k8s_secrets"
  vars: 
    namespace: "{{ component_ns }}"    
    check: "docker_credentials"
  when: 
  - network.docker.username is defined
