##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

---
# This populates the nodeid details
- name: Get nodeid details from Vault
  include_tasks: nested_main.yaml
  loop: "{{ org.services.peers }}"
  loop_control:
    loop_var: peer
  when: 
  - peer.type == "member"
  - peer.persona is defined
