apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inteli-api.fullname" . }}-config
  labels:
    {{- include "inteli-api.labels" . | nindent 4 }}
data:
  port: {{ .Values.config.port | quote }}
  dscpApiHost: {{ .Values.config.dscpApiHost }}
  dscpApiPort: {{ .Values.config.dscpApiPort | quote }}
  logLevel: {{ .Values.config.logLevel }}
  dbHost: {{ include "inteli-api.postgresql.fullname" . }}
  dbPort: {{ .Values.config.dbPort | quote }}
  dbName: {{ .Values.config.dbName }}
  {{- if eq .Values.config.auth.type "JWT" }}
  authJwksUri: {{ .Values.config.auth.jwksUri }}
  authAudience: {{ .Values.config.auth.audience }}
  authIssuer: {{ .Values.config.auth.issuer }}
  authTokenUrl: {{ .Values.config.auth.tokenUrl }}
  {{- end }}
  identityServiceHost: {{ .Values.config.identityServiceHost }}
  identityServicePort: {{ .Values.config.identityServicePort | quote }}
  externalAddress: {{ .Values.config.externalAddress }}
  authType: {{ .Values.config.auth.type }}
