##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

#############################################################################################
# This role deletes the Vault configurations
#############################################################################################

#############################################################################################

# Delete the Docker credentials
- name: Delete docker creds
  k8s:
    kind: Secret
    namespace: "{{ org_namespace }}"
    name: "regcred"
    state: absent
    kubeconfig: "{{ kubernetes.config_file }}"
    context: "{{ kubernetes.context }}"
  ignore_errors: yes

# Delete Ambassador creds
- name: Delete Ambassador creds
  k8s:
    kind: Secret
    namespace: "{{ org_namespace }}"
    name: "{{ peer.name }}-ambassador-certs"
    kubeconfig: "{{ kubernetes.config_file }}"
    context: "{{ kubernetes.context }}"
    state: absent
  loop: "{{ services.peers }}"
  loop_control:
    loop_var: peer
  ignore_errors: yes

# Delete crypto materials
- name: Delete Crypto materials
  shell: |
    vault kv delete {{ item.vault.secret_path | default('secretsv2') }}/{{ org_name }}/crypto/{{ peer.name }}/tm
    vault kv delete {{ item.vault.secret_path | default('secretsv2') }}/{{ org_name }}/crypto/{{ peer.name }}/quorum
    vault kv delete {{ item.vault.secret_path | default('secretsv2') }}/{{ org_name }}/crypto/{{ peer.name }}/certs
    vault kv delete {{ item.vault.secret_path | default('secretsv2') }}/{{ org_name }}/crypto/genesis
  loop: "{{ services.peers }}"
  environment:
    VAULT_ADDR: "{{ item.vault.url }}"
    VAULT_TOKEN: "{{ item.vault.root_token }}"
  loop_control:
    loop_var: peer
  ignore_errors: yes
