- name: Initialize first_member_peer to empty string
  set_fact:
    first_member_org: ""
    first_member_peer: ""
    ipfs_bootnode_name: ""
    count: 0
    # node_list: []

- name: "Generate IPFS BOOTNODE endpoint"
  include_tasks: nested.yaml
  vars:
    generate_ipfs_url: true
    org: "{{ item }}"
    org_name: "{{ org.name | lower }}"
    component_ns: "{{ org.name | lower }}-subs"
    vault: "{{ org.vault }}"
  loop: "{{ network['organizations'] }}"
  when: network.config.node_image == "inteli-poc/dscp-node"

- name: pause
  pause:
    minutes: 2

- name: "Deploy ipfs bootnodes- main.yaml"
  include_tasks: nested.yaml
  vars:
    generate_ipfs_url: false
    org: "{{ item }}"
    org_name: "{{ org.name | lower }}"
    vault: "{{ org.vault }}"
    peers: "{{ org.services.peers }}"
    gitops: "{{ org.gitops }}"
    component_name: "{{ org.name | lower }}"
    component_ns: "{{ org.name | lower }}-subs"
    build_path: "./build"
    charts_dir: "{{ org.gitops.chart_source }}"
    values_dir: "{{ playbook_dir }}/../../../{{ org.gitops.release_dir }}/{{ org.name | lower }}"
  loop: "{{ network['organizations'] }}"
  when: network.config.node_image == "inteli-poc/dscp-node"
